Subscribe block digest endpoints
onflow/flow-go-sdk pull request #764
Opened 2024-09-23 08:50 UTC by AndriiDiachuk

Part of #746.

2024-09-25 15:03 UTC, janezpodhostnik requested changes

2024-09-25 15:03 UTC, janezpodhostnik commented on access/grpc/grpc.go
> +			sendErr(fmt.Errorf("error receiving blockHeader: %w", err))
```suggestion
			sendErr(fmt.Errorf("error receiving blockDigest: %w", err))
```

2024-09-26 10:04 UTC, janezpodhostnik approved these changes

2024-10-03 17:10 UTC, peterargue commented on access/grpc/grpc.go
> +		BlockStatus:  convert.BlockStatusToEntity(blockStatus),
These should only allow finalized or sealed as the status. otherwise, return an error

2024-10-09 17:53 UTC, peterargue commented
@AndriiDiachuk please fix conflicts, then this is ready to merge

2024-10-15 18:05 UTC, peterargue approved these changes

2024-10-15 18:05 UTC, merged